### PR TITLE
update ui layout for user pages (profile, connected, and notifications)

### PR DESCRIPTION
**Pull request by jpoechill**
**What is this?**

This PR updates and cleans up the layouts for a set of the _user_ pages – including for profile (also change password page), connected, and notifications. Care has also been given to pages for responsiveness.

**What does it do?**

All page updates are cosmetic base and does not touch application logic.

**What is the current behavior?**

Some dashboard pages lack proper spacing between elements, and are inconsistent in form input sizes. In some instances spacing between elements are underutilized.

**What is the expected behavior?**

Dashboard pages should have content that is evenly aligned and fit a standard, consistent grid system.

--

Supplement Screenshots 

user-dash-profile
user-dash-connected
user-dash-notifications

user-dash-profile-change-password

### CODE REVIEW

**Comment by jpoechill** [comment]
also fixes both concerns in #150.

ready to go.

**Comment by smirolo** [comment]
Layout issues on profile page when looking at http://localhost:8020/profile/djaoapp/contact/ while logged in as alice/yoyo.
Screen Shot 2019-10-11 at 3 42 52 PM
We also need to be thoughtful about the information that goes in the left column vs. the right column (name, email vs. address? and/or user accessible vs. admin accessible, aka notes?)

**Comment by jpoechill** [comment]
Updated.

--

My original intent with columned layouts was to start to introduce a consistent grid system to the layouts. I think starting to move forward (and on the track of _mobile first_) we can begin to make everything easier by adopting a singe column layout where abled.

Some references:
[https://baymard.com/blog/avoid-multi-column-forms](https://baymard.com/blog/avoid-multi-column-forms
)
[https://uxplanet.org/the-18-must-do-principles-in-the-form-design-fe89d0127c92](https://uxplanet.org/the-18-must-do-principles-in-the-form-design-fe89d0127c92)

Will be hoping to review these and explore/mock-out some future options.

**Comment by smirolo** [comment]
As a single commit 76365627

**Pull request closed without merging**
