### PR TITLE
Vue views

### PR DESCRIPTION
**Pull request by knivets**

### CODE REVIEW

**Comment by knivets** [comment]
This PR is still work in progress because it depends on the other PR https://github.com/djaodjin/djaodjin-saas/pull/153

**Comment by knivets** [comment]
OK, this one should be ready for review.

**Comment by knivets** [comment]
Actually, it makes sense to merge this one first https://github.com/djaodjin/djaodjin-signup/pull/18

**Comment by smirolo** [comment]
Merged into bootstrap4-vue branch.

**Pull request closed without merging**
