### PR TITLE
update ui layout for admin pages (dashboard, coupons, funds, themes and rules)

### PR DESCRIPTION
**Pull request by jpoechill**
**What is this?**

This PR updates and cleans up the layouts for a set of the admin pages – including for dashboard, coupons, funds, themes, and rules. Care has also been given to pages for responsiveness.

**What does it do?**

All page updates are cosmetic base and does not touch application logic.

**What is the current behavior?**

Some dashboard pages lack proper spacing between elements, and are inconsistent in form input sizes. In some instances spacing between elements are underutilized.

**What is the expected behavior?**

Dashboard pages should have content that is evenly aligned and fit a standard, consistent grid system.

--

Supplement Screenshots (also seen in DD Slack channel)

screencapture-djaoapp-localhost-8000-metrics-djaoapp-dashboard-2019-09-16-12_22_00
screencapture-djaoapp-localhost-8000-billing-djaoapp-coupons-2019-09-16-12_21_29
screencapture-djaoapp-localhost-8000-billing-djaoapp-transfers-2019-09-16-12_22_29
screencapture-djaoapp-localhost-8000-themes-2019-09-16-12_23_55
screencapture-djaoapp-localhost-8000-proxy-rules-2019-09-16-12_24_14

### CODE REVIEW

**Comment by smirolo** [comment]
99% of the time a support person will land on the dashboard to look up for a customer. The search box thus needs to be at the top of the page. Most times a customer will contact support within minutes of stumbling upon an issue. "Recently Active Users" is a list of shortcuts to users recently logged in or that were charged. The goal of the "Recently Active Users" is to go even faster for a support person (no need to type in search box).

dashboard-iphonex
The layout of the dashboard needs to be reverted back to previous setup, or updated to move "search" and  "Recently Active Users" above the fold on mobile.

**Comment by smirolo** [comment]
Screen Shot 2019-10-02 at 10 51 13 AM

**Comment by jpoechill** [comment]
Fixed the Dashboard and Coupons page as can be seen in shots below.

1. For the _Dashboard_ page, order of the page elements have been reversed, bringing search to the top of page.
2. For the _Coupons_ page, input elements have been returned to original order, though adjusting for size consistency and updating copy for clarity.

Po–

dd_screenshot_02_100719
dd_screenshot_100719

**Comment by smirolo** [comment]
as a single commit 76365627.

**Pull request closed without merging**
